name = "ordinals-trade-ledger"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "6a0bf22a5ff120f19789f29eb4196ce2"

[[d1_databases]]
binding = "DB"
database_name = "ordinals-trade-ledger"
database_id = "aa569031-1697-48b5-a8ce-2c23ed3a90bb"

[vars]
CORS_ORIGIN = "*"
